workflows:
  android-release:
    name: Build Android Release
    max_build_duration: 30
    environment:
      flutter: stable
      groups:
        - finqly_signing
      android_signing:
        - finqly_keystore   # ← OK（署名キーグループ）
    scripts:
      - name: Get packages
        script: |
          flutter pub get
      - name: Generate launcher icons
        script: |
          flutter pub run flutter_launcher_icons:main
      - name: Build release AAB
        script: |
          flutter build appbundle --release   # ← ここを変更！
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab  # ← AABの出力先
