workflows:
  android-release:
    name: Build Android Release
    max_build_duration: 30
    environment:
      flutter: stable
      groups:
        - finqly_signing   # CM_KEYSTORE_BASE64 / CM_KEYSTORE_PASSWORD / CM_KEY_ALIAS / CM_KEY_PASSWORD
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.gradle/caches
        - ~/.gradle/wrapper

    scripts:
      - name: Restore keystore from env
        script: |
          set -euo pipefail
          if [ -z "${CM_KEYSTORE_BASE64:-}" ]; then
            echo "CM_KEYSTORE_BASE64 is missing"; exit 1
          fi
          echo "$CM_KEYSTORE_BASE64" | base64 -d > /tmp/my-release-key.jks
          export CM_KEYSTORE="/tmp/my-release-key.jks"
          ls -l "$CM_KEYSTORE"

      - name: Write android/key.properties
        script: |
          set -euo pipefail
          mkdir -p android
          cat > android/key.properties <<EOF
          storeFile=$CM_KEYSTORE
          storePassword=$CM_KEYSTORE_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          keyPassword=$CM_KEY_PASSWORD
          EOF
          echo "Wrote android/key.properties:"
          sed 's/=.*/=*** (redacted)/' android/key.properties

      - name: Flutter pub get
        script: flutter pub get

      - name: Build AAB (release)
        script: |
          mkdir -p build/symbols
          flutter build appbundle --release \
            --tree-shake-icons \
            --split-debug-info=build/symbols

      - name: Verify AAB signature
        script: |
          test -f build/app/outputs/bundle/release/app-release.aab
          jarsigner -verify -verbose -certs build/app/outputs/bundle/release/app-release.aab

    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
      - build/symbols/**
