workflows:
  android-release:
    name: Build Android Release
    max_build_duration: 30
    environment:
      flutter: stable
      java: 17
      groups:
        - finqly_signing       # CM_KEYSTORE_BASE64 / CM_KEYSTORE_PASSWORD / CM_KEY_ALIAS / CM_KEY_PASSWORD
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.gradle/caches
        - ~/.gradle/wrapper

    scripts:
      - name: Print toolchain versions
        script: |
          set -e
          flutter --version
          java -version
          echo "JAVA_HOME=${JAVA_HOME:-unset}"
          gradle -v || true

      - name: Restore keystore from env (robust)
        script: |
          set -euo pipefail
          : "${CM_KEYSTORE_BASE64:?CM_KEYSTORE_BASE64 missing}"
          : "${CM_KEYSTORE_PASSWORD:?CM_KEYSTORE_PASSWORD missing}"
          : "${CM_KEY_ALIAS:?CM_KEY_ALIAS missing}"
          : "${CM_KEY_PASSWORD:?CM_KEY_PASSWORD missing}"

          CLEAN_B64="$(printf '%s' "$CM_KEYSTORE_BASE64" | tr -d '\r\n')"
          if printf '%s' "$CLEAN_B64" | base64 --decode > /tmp/my-release-key.jks 2>/dev/null; then
            :
          elif printf '%s' "$CLEAN_B64" | base64 -d > /tmp/my-release-key.jks 2>/dev/null; then
            :
          else
            echo "::error:: Failed to decode CM_KEYSTORE_BASE64. Check for hidden whitespace or truncation."
            exit 1
          fi

          export CM_KEYSTORE="/tmp/my-release-key.jks"
          echo 'CM_KEYSTORE=/tmp/my-release-key.jks' >> "$CM_ENV"
          ls -l "$CM_KEYSTORE"

          keytool -list -v -keystore "$CM_KEYSTORE" -storepass "$CM_KEYSTORE_PASSWORD" >/dev/null

          ALIAS_LIST=$(keytool -list -v -keystore "$CM_KEYSTORE" -storepass "$CM_KEYSTORE_PASSWORD" | grep -i "^Alias name:" | awk '{print $3}')
          echo "[signing] Found alias(es): $ALIAS_LIST"
          if ! echo "$ALIAS_LIST" | grep -Fxq "$CM_KEY_ALIAS"; then
            echo "::warning:: CM_KEY_ALIAS ($CM_KEY_ALIAS) not found in keystore aliases ($ALIAS_LIST)."
          fi

          echo "[signing] Keystore restored and storepass verified."

      - name: Ensure clean key.properties (avoid stale file)
        script: |
          set -euo pipefail
          rm -f android/key.properties || true
          mkdir -p android

      - name: Write android/key.properties
        script: |
          set -euo pipefail
          : "${CM_KEYSTORE:?CM_KEYSTORE missing}"
          : "${CM_KEYSTORE_PASSWORD:?CM_KEYSTORE_PASSWORD missing}"
          : "${CM_KEY_ALIAS:?CM_KEY_ALIAS missing}"
          : "${CM_KEY_PASSWORD:?CM_KEY_PASSWORD missing}"

          cat > android/key.properties <<EOF
          storeFile=${CM_KEYSTORE}
          storePassword=${CM_KEYSTORE_PASSWORD}
          keyAlias=${CM_KEY_ALIAS}
          keyPassword=${CM_KEY_PASSWORD}
          EOF

          echo "Wrote android/key.properties:"
          sed 's/=.*/=*** (redacted)/' android/key.properties

      - name: Flutter pub get
        script: flutter pub get

      - name: Flutter clean (optional)
        script: |
          set -e
          flutter clean
          rm -rf build || true

      - name: Build AAB (release)
        script: |
          set -e
          mkdir -p build/symbols
          flutter build appbundle --release \
            --tree-shake-icons \
            --split-debug-info=build/symbols
            # --no-shrink

      - name: Verify AAB signature
        script: |
          set -e
          AAB=build/app/outputs/bundle/release/app-release.aab
          test -f "$AAB"
          jarsigner -verify -verbose -certs "$AAB" | sed -n '1,40p'
          echo "[signing] AAB signature verified."

    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
      - build/symbols/**
