workflows:
  android-release:
    name: Build Android Release
    max_build_duration: 30
    environment:
      flutter: stable
      groups:
        - finqly_signing   # CM_KEYSTORE_BASE64 / CM_KEYSTORE_PASSWORD / CM_KEY_ALIAS / CM_KEY_PASSWORD
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.gradle/caches
        - ~/.gradle/wrapper
    scripts:
      - name: Restore keystore
        script: |
          if [ -z "$CM_KEYSTORE_BASE64" ]; then
            echo "CM_KEYSTORE_BASE64 is missing"; exit 1
          fi
          echo "$CM_KEYSTORE_BASE64" | base64 -d > /tmp/my-release-key.jks
          echo "CM_KEYSTORE=/tmp/my-release-key.jks" >> $CM_ENV

      - name: Write key.properties (fallback)
        script: |
          for v in CM_KEYSTORE_PASSWORD CM_KEY_ALIAS CM_KEY_PASSWORD; do
            if [ -z "${!v}" ]; then echo "Missing env: $v"; exit 1; fi
          done
          cat > android/key.properties <<EOF
storeFile=/tmp/my-release-key.jks
storePassword=$CM_KEYSTORE_PASSWORD
keyAlias=$CM_KEY_ALIAS
keyPassword=$CM_KEY_PASSWORD
EOF
          echo "Wrote android/key.properties"

      - name: Flutter pub get
        script: flutter pub get

      - name: (optional) Generate l10n
        script: flutter gen-l10n

      - name: (optional) Static analysis (won't fail build)
        script: flutter analyze || true

      - name: Build AAB (release)
        script: |
          mkdir -p build/symbols
          flutter build appbundle --release \
            --tree-shake-icons \
            --split-debug-info=build/symbols

      - name: Verify AAB signature
        script: |
          AAB=build/app/outputs/bundle/release/app-release.aab
          if [ ! -f "$AAB" ]; then echo "AAB not found"; exit 1; fi
          jarsigner -verify -verbose -certs "$AAB"
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
      - build/symbols/**
