workflows:
  android-release:
    name: Build Android Release
    max_build_duration: 30
    environment:
      flutter: stable
      groups:
        - finqly_signing
      android_signing:
        - finqly_keystore
    scripts:
      - name: Get packages
        script: |
          flutter pub get
      - name: Generate launcher icons
        script: |
          flutter pub run flutter_launcher_icons:main
      - name: Build release AAB
        script: |
          flutter build appbundle --release
      - name: Build release APK         # ← 追加
        script: |
          flutter build apk --release   # ← 追加
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
      - build/app/outputs/flutter-apk/app-release.apk    # ← APKも成果物に追加
