workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
      groups:
        - finqly_signing
      android_signing:
        - finqly_keystore
    scripts:
      - name: Clean build cache
        script: |
          flutter clean

      - name: Install dependencies
        script: |
          flutter pub get

      - name: Generate localization files
        script: |
          flutter gen-l10n

      - name: Build APK
        script: |
          flutter build apk --release --target=lib/main.dart

      - name: Build AAB
        script: |
          flutter build appbundle --release --target=lib/main.dart

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab

android_signing:
  finqly_keystore:
    path: finqly-release-key.jks
    keystore: CM_KEYSTORE
    keystore_password: CM_KEYSTORE_PASSWORD
    key_alias: CM_KEY_ALIAS
    key_password: CM_KEY_PASSWORD
    groups:
      - finqly_signing
