workflows:
  android-release:
    name: Build Android Release
    max_build_duration: 30
    environment:
      flutter: stable
      groups:
        - finqly_signing
    scripts:
      - name: Restore keystore & Build
        script: |
          echo $CM_KEYSTORE_BASE64 | base64 -d > /tmp/my-release-key.jks
          export CM_KEYSTORE="/tmp/my-release-key.jks"
          flutter pub get
          flutter pub run flutter_launcher_icons:main
          flutter build appbundle --release
          flutter build apk --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
      - build/app/outputs/flutter-apk/app-release.apk
