workflows:
  android-release:
    name: Build Android Release
    max_build_duration: 30
    environment:
      flutter: stable
      groups:
        - finqly_signing
      android_signing:
        - finqly_keystore   # ← 修正済（以前: finqly_signing）
    scripts:
      - name: Get packages
        script: |
          flutter pub get
      - name: Generate launcher icons
        script: |
          flutter pub run flutter_launcher_icons:main
      - name: Build release APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
