workflows:
  android-release:
    name: Build Android Release
    max_build_duration: 30
    environment:
      flutter: stable
      groups:
        - finqly_keystore
      android_signing:
        - finqly_keystore
    scripts:
      - name: Get packages
        script: |
          flutter pub get
      - name: Build release APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
