workflows:
  android-release:
    name: Build Android Release
    max_build_duration: 30
    environment:
      flutter: stable
      groups:
        - finqly_signing   # CM_KEYSTORE_BASE64 / CM_KEYSTORE_PASSWORD / CM_KEY_ALIAS / CM_KEY_PASSWORD
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.gradle/caches
        - ~/.gradle/wrapper
    scripts:
      - name: Restore keystore
        script: |
          if [ -z "$CM_KEYSTORE_BASE64" ]; then
            echo "CM_KEYSTORE_BASE64 is missing"; exit 1
          fi
          echo "$CM_KEYSTORE_BASE64" | base64 -d > /tmp/my-release-key.jks
          export CM_KEYSTORE="/tmp/my-release-key.jks"

      - name: Flutter pub get
        script: flutter pub get

      - name: (optional) Generate l10n
        script: flutter gen-l10n

      - name: (optional) Static analysis (won't fail build)
        script: flutter analyze || true

      - name: Build AAB (release)
        script: |
          mkdir -p build/symbols
          flutter build appbundle --release \
            --tree-shake-icons \
            --split-debug-info=build/symbols

      - name: Verify AAB signature
        script: |
          if [ ! -f build/app/outputs/bundle/release/app-release.aab ]; then
            echo "AAB not found"; exit 1
          fi
          jarsigner -verify -verbose -certs build/app/outputs/bundle/release/app-release.aab

      # - name: Build APK
      #   script: flutter build apk --release --tree-shake-icons --split-debug-info=build/symbols

    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
      - build/symbols/**
