name: finqly
description: Finqly helps you understand your emotions and forecast your financial mindset.
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  in_app_purchase: ^3.1.5
  shared_preferences: ^2.2.2
  fl_chart: ^0.65.0
  package_info_plus: ^5.0.1
  webview_flutter: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/finqly_logo.png
    - assets/images/badges/cautious.png
    - assets/images/badges/confused.png
    - assets/images/badges/excited.png
    - assets/images/badges/neutral.png
    - assets/images/badges/optimistic.png
    - assets/images/badges/worried.png
    - assets/legal/privacy.html
    - assets/legal/terms.html
    - assets/legal/legal_center.html
    - assets/legal/disclaimer.html
    - assets/legal/faq.html

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/finqly_logo.png"
