name: Android build (pub get + debug APK)

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.6
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Auto-commit lockfile
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: flutter pub get (lockfile update)"

      - name: Build debug APK
        run: flutter build apk --debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
